name: validate
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  schema:
    name: AJV schema checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i -g ajv-cli@5
      - name: Validate examples
        run: |
          ajv validate -s schema/hgl-glyph-spec-1.0.json -d examples/glyph-doc-hello.json
          ajv validate -s schema/hgl-error-taxonomy-1.0.json -d examples/error-emit-HGL-ERR-0103.json
          ajv validate -s schema/hgl-hop-decision-1.0.json -d examples/hop-decision.json

  docs:
    name: Docs lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: avto-dev/markdown-lint@v1
